### ISSUE TITLE
Fails when trying to cloak StandIn

### ISSUE THREAD

**Issue by davidmckennirey** [h4wkst3r/InvisibilityCloak#1]
Hello and thanks for the tool! I just watched your talk on C# obfuscation, and I wanted to attempt it myself. However, when I attempted to build StandIn (https://github.com/FuzzySecurity/StandIn) after being obfuscated, I got many syntax errors. For example:

L969:
```
sTaskContent = String.Format(new string(@"<VzzrqvngrGnfxI2 pyfvq=".Select(xAZ => (xAZ >= 'a' && xAZ <= 'z') ? (char)((xAZ - 'a' + 13) % 26 + 'a') : ((xAZ >= 'A' && xAZ <= 'Z') ? (char)((xAZ - 'A' + 13) % 26 + 'A') : xAZ)).ToArray())new string("
```

Here I am getting a "Syntax error, ',' expected" error between the end of the first `string([...])` and the next `new string`. I have a few hundred of these in my build log.

**Comment by h4wkst3r** [comment]
Just fixed this with this minor code tweak, so it is good to go now!

https://github.com/h4wkst3r/InvisibilityCloak/commit/40a976954c56e67695bc4847780b1c3c372a2d2c

**Comment by h4wkst3r** [comment]
If you have any other issues, just let me know @davidmckennirey, and I can close this issue

**Comment by davidmckennirey** [comment]
Just pulled and tried again, works like a charm! Thanks for the quick fix 😄

**Comment by h4wkst3r** [comment]
Absolutely, thanks for bringing up the issue!
