### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: ''

### ISSUE THREAD

**Issue by 0x73unflower** [h4wkst3r/InvisibilityCloak#8]
When running `python .\InvisibilityCloak.py -d C:\Users\x\source\repos\juicy-potato2\ -n "BitterOrange" -m reverse` I seem to be getting an error as stated below:

`Traceback (most recent call last):
  File "E:\Tools\InvisibilityCloak\InvisibilityCloak.py", line 542, in <module>
    main(theObfMethod, theDirectory, theName)
  File "E:\Tools\InvisibilityCloak\InvisibilityCloak.py", line 497, in main
    replaceGUIDAndToolName(theDirectory, theName)
  File "E:\Tools\InvisibilityCloak\InvisibilityCloak.py", line 122, in replaceGUIDAndToolName
    copyfile(csProjFile, f"{csProjFile}")
  File "C:\msys64\mingw64\lib\python3.10\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: ''`

I'm trying to obfuscate [JuicyPotato](https://github.com/ohpe/juicy-potato) but it fails. I tried the same syntax, but on a different tool - [SweetPotato](https://github.com/CCob/SweetPotato) and it obfuscated the .sln with the reverse method just fine.

Why do some tools raise this error? The projects are under the same parent directory - C:\Users\x\source\repos and one compiles whereas the other doesn't.

**Comment by h4wkst3r** [comment]
Hi @copywrited - This tool is for obfuscating C# projects. It looks like the JuicyPotato project is a C++ project, and is therefore not supported.
